#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations
from pathlib import Path
import re

BOARD = Path("docs/board/PROJECT_BOARD.md")

# Canonical truth should come from AUTO:PROGRESS block (generated by task-truth sync)
AP_BEGIN = "<!-- AUTO:PROGRESS_BEGIN -->"
AP_END   = "<!-- AUTO:PROGRESS_END -->"

# Patch tasks are tracked separately
P_BEGIN = "<!-- AUTO_PATCH_TASKS_START -->"
P_END   = "<!-- AUTO_PATCH_TASKS_END -->"

TASK_RX = re.compile(r"^\s*[-*+]\s*\[([ xX~!])\]\s*\[TASK:([^\]]+)\]")

def _read_auto_progress(board_text: str) -> dict:
    b = board_text.find(AP_BEGIN)
    e = board_text.find(AP_END, b + 1)
    if b < 0 or e < 0 or e <= b:
        return {}
    block = board_text[b:e].splitlines()
    out = {}
    for ln in block:
        # lines like: - **TOTAL:** 80
        m = re.search(r"\*\*(TOTAL|DONE|DOING|BLOCKED|TODO|PCT)\:\*\*\s*([0-9.]+)", ln)
        if m:
            k = m.group(1).upper()
            v = m.group(2)
            out[k] = float(v) if "." in v else int(v)
    return out

def _count_patch_tasks(board_text: str) -> dict:
    b = board_text.find(P_BEGIN)
    e = board_text.find(P_END, b + 1)
    if b < 0 or e < 0 or e <= b:
        return {"total":0,"done":0,"doing":0,"blocked":0,"todo":0}
    block = board_text[b:e].splitlines()
    patch = {"total":0,"done":0,"doing":0,"blocked":0,"todo":0}
    for ln in block:
        m = TASK_RX.match(ln)
        if not m:
            continue
        mark = m.group(1)
        patch["total"] += 1
        if mark in ("x","X"):
            patch["done"] += 1
        elif mark == "~":
            patch["doing"] += 1
        elif mark == "!":
            patch["blocked"] += 1
        else:
            patch["todo"] += 1
    return patch

def main() -> None:
    text = BOARD.read_text(encoding="utf-8", errors="replace")

    ap = _read_auto_progress(text)
    if not ap:
        raise SystemExit("[FATAL] missing AUTO:PROGRESS block; cannot derive canonical counts")

    total = int(ap.get("TOTAL", 0))
    done = int(ap.get("DONE", 0))
    doing = int(ap.get("DOING", 0))
    blocked = int(ap.get("BLOCKED", 0))
    todo = int(ap.get("TODO", 0))
    pct = float(ap.get("PCT", (done/total*100.0 if total else 0.0)))

    patch = _count_patch_tasks(text)

    print("[CANON] total={} done={} doing={} blocked={} todo={} pct={:.1f}%".format(
        total, done, doing, blocked, todo, pct
    ))
    print("[PATCH] total={} done={} doing={} blocked={} todo={}".format(
        patch["total"], patch["done"], patch["doing"], patch["blocked"], patch["todo"]
    ))

if __name__ == "__main__":
    main()
