#!/usr/bin/env bash
set -euo pipefail
cd "$HOME/tmf_autotrader"

LOGDIR="$HOME/tmf_autotrader/runtime/logs"
mkdir -p "$LOGDIR"
OUT="$LOGDIR/daily_finance_close_pack_v1.out.log"
ERR="$LOGDIR/daily_finance_close_pack_v1.err.log"

exec >>"$OUT" 2>>"$ERR"

echo "=== [daily_finance_close_pack_v1] start $(date '+%F %T') ==="

# 1) build close pack (zip + sidecar)
bash "$HOME/tmf_autotrader/scripts/build_daily_finance_close_pack_v1.sh"

# pick latest zip
ZIP="$(ls -1t runtime/close_pack/DAILY_FINANCE_CLOSE_PACK_*.zip 2>/dev/null | head -n 1 || true)"
if [[ -z "${ZIP}" || ! -f "${ZIP}" ]]; then
  echo "[FAIL] cannot find latest close pack zip under runtime/close_pack/"
  exit 2
fi

# verify sidecar exists
SIDECAR="${ZIP}.sha256.txt"
if [[ ! -f "${SIDECAR}" ]]; then
  echo "[FAIL] missing sidecar: ${SIDECAR}"
  exit 3
fi

# 2) write OFFICIAL snapshot (md + sha256)
TS="$(date '+%Y%m%d_%H%M%S')"
SNAP="docs/ops/DAILY_FINANCE_CLOSE_PACK_OFFICIAL_SNAPSHOT_${TS}.md"
SNAP_SHA="${SNAP}.sha256.txt"

cat > "${SNAP}" <<EOF
# DAILY_FINANCE_CLOSE_PACK OFFICIAL SNAPSHOT
- ts: $(date '+%F %T')
- pack_zip: ${ZIP}
- pack_sha256_sidecar: ${SIDECAR}

## Notes
- Generated by: scripts/run_daily_finance_close_pack_daily_v1.sh
- This snapshot is append-only indexed by docs/ops/OPS_INDEX.md
EOF

( cd "$(dirname "$SNAP")" && shasum -a 256 "$(basename "$SNAP")" > "$(basename "$SNAP_SHA")" )

echo "[OK] wrote snapshot: ${SNAP}"
echo "[OK] wrote snapshot sidecar: ${SNAP_SHA}"

# 3) append OPS_INDEX.md (idempotent)
python3 - <<'PY'
from pathlib import Path
import re

ops = Path("docs/ops/OPS_INDEX.md")
ops.parent.mkdir(parents=True, exist_ok=True)
if not ops.exists():
    ops.write_text("# OPS INDEX\n\n", encoding="utf-8")

txt = ops.read_text(encoding="utf-8", errors="replace")

# find latest snapshot + close pack zip
snap = sorted(Path("docs/ops").glob("DAILY_FINANCE_CLOSE_PACK_OFFICIAL_SNAPSHOT_*.md"))[-1].as_posix()
snap_sha = snap + ".sha256.txt"
zips = sorted(Path("runtime/close_pack").glob("DAILY_FINANCE_CLOSE_PACK_*.zip"))
zip_path = zips[-1].as_posix()
zip_sha = zip_path + ".sha256.txt"

lines_to_add = [
    f"- Daily Finance Close Pack (zip+sha256): {Path(zip_path).name} / {Path(zip_sha).name}",
    f"- DAILY_FINANCE_CLOSE_PACK OFFICIAL snapshot (md+sha256): {Path(snap).name} / {Path(snap_sha).name}",
]

# append only if missing
out_lines = txt.splitlines()
added = 0
for l in lines_to_add:
    if not any(x.strip() == l.strip() for x in out_lines):
        out_lines.append(l)
        added += 1

ops.write_text("\n".join(out_lines).rstrip() + "\n", encoding="utf-8")
print(f"[OK] OPS_INDEX append added={added}")
PY

# 4) insert TASK into PROJECT_BOARD.md (idempotent)
python3 - <<'PY'
from pathlib import Path
import re

p = Path("docs/board/PROJECT_BOARD.md")
if not p.exists():
    raise SystemExit("[FAIL] missing docs/board/PROJECT_BOARD.md")

txt = p.read_text(encoding="utf-8", errors="replace")
task_pat = r"\[TASK:PM\].*Daily Finance Close Pack AUTO daily agent v1.*com\.tmf_autotrader\.daily_finance_close_pack_v1"
if re.search(task_pat, txt):
    print("[OK] TASK already exists (skip)")
    raise SystemExit(0)

task_line = "- [x] [TASK:PM] Daily Finance Close Pack AUTO daily agent v1 + kickstart smoke (2026-02-04) (LaunchAgent=com.tmf_autotrader.daily_finance_close_pack_v1)\n"

# insert before first TASK:PM if present, else append near top after header block
m = re.search(r"(?m)^\s*-\s*\[[ xX]\]\s*\[TASK:PM\]", txt)
if m:
    idx = m.start()
    txt2 = txt[:idx] + task_line + txt[idx:]
else:
    txt2 = txt.rstrip() + "\n" + task_line

p.write_text(txt2, encoding="utf-8")
print("[OK] inserted TASK into PROJECT_BOARD.md")
PY

# 5) refresh board (so header reflects new totals)
./scripts/pm_refresh_board_canonical.sh close_pack_tick >/dev/null 2>&1 || true

echo "=== [daily_finance_close_pack_v1] done $(date '+%F %T') ==="
